feat: Add .dryrun Command Support #156
permaweb/aos pull request #191
Opened 2024-03-14 19:36 UTC by mayurmarvel

### Description
This pull request addresses issue #156 by introducing support for the `.dryrun` command in the `aos` project. Below is a summary of the changes made:

#### Files Modified / Created:
- `/src/index.js`: Added support for `.dryrun` command.
- `/src/commands/dryrun.js`: Implemented the functionality for the `.dryrun` command.
- `/src/commands/dryrun.md`: Created a usage guide for the `.dryrun` command.
- `README.md`: Updated commands list to include `.dryrun`.
- `/src/services/help.js`: Added `.dryrun` to the help list.

**For the full usage guide and detailed changes, please refer to** `/src/commands/dryrun.md`.

### Syntax Example
      .dryrun ({ Target = 'FgU-RiEaLuC__SHZnI9pSIa_ZI8o-8hUVG9nPJvs92k', Action = 'Balance' })

      .dryrun {Balance}

### Flags List:
- `-p`: Specifies Process ID.
- `-d`: Specifies data.
- `-r`: Accesses the Result Object.
- `-v`: Views the DryRun Parameters.

### Functions:
- `dryrun`: Executes a dry run to query Processes without sending a message.

### Testing
Performed manual testing to ensure the functionality of the `.dryrun` command in various scenarios.

### Features That Can Be Added
- A loading spinner can be added if needed.

### Related Issue
Closes #156

2024-03-19 02:51 UTC, twilson63 approved these changes

2024-03-22 00:41 UTC, allquantor requested changes
Added a couple of comments. 
I would re-iterate to reduce overall complexity. A lot of stuff to simplify. 
Good job

2024-03-22 00:41 UTC, allquantor commented on src/commands/dryrun.js
> +const getCustomProcessId = (input, pid) => {
Slightly cleaner. 
```
const getCustomProcessId = (input, pid) => {
  const match = input.match(/-p=(["'])(.*?)\1/);
  if (!match) return null;
  const customProcessId = match[2] === "ao.id" ? pid : match[2];
  if (customProcessId.length !== 43) throw new Error("Invalid Process Id");
  return customProcessId;
};
```

2024-03-22 00:41 UTC, allquantor commented on src/commands/dryrun.js
> +    console.error(chalk.red("Error Performing DryRun:", error.message));
Would it not be right to propagate the error up in context? Why swallow it here.

2024-03-22 00:41 UTC, allquantor commented on src/commands/dryrun.js
> +async function extractTags(input, pid) {
P.S if target can be appended you can get rid of else al in all 

```
if (!input.includes("{")) throw new Error("Tags not specified");

  const content = input.match(/\{(.*?)\}/)?.[1];
  if (!content) throw new Error("Invalid Syntax Usage");

  return content.split(",").map(pair => {
    const [key, rawValue] = pair.includes("=") ? pair.split("=") : ["Action", pair];
    const value = rawValue.trim().replace(/^['"](.*)['"]$/, "$1").replace(/^ao\.id$/, pid);
    return { name: key.trim(), value };
  }).concat({ name: "Target", value: pid });
  ```

2024-03-22 12:47 UTC, mayurmarvel commented on README.md
> +[evolutionary forking](https://arweave.medium.com/arweave-is-an-evolutionary-protocol-e072f5e69eaa)s
Sorry, that's a typo.

2024-04-15 21:20 UTC, twilson63 commented
🤔 I think this can be a simpler fix, if you spawn the process and you are not the owner, you can open the process in (Read-Only) mode by default, which means, that instead of sending messages, you send `dryrun`s - so you will not be able to perform any write capable functions, because you are not the Owner, but you will be able to inspect the process and visually view the state?

@allquantor @mayurmarvel - What do you think?

For example, if I call `aos {pid}` and I don't have `Eval` privileges, then aos does `dryrun` be default?

2024-09-20 02:15 UTC, closed without merging